behaviors:
  MovetoGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 1.0e-4 # Adjusted learning rate
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true # Use normalized inputs
      hidden_units: 256 # Increased hidden units
      num_layers: 3 # Increased number of layers
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000 # Increased max steps
    time_horizon: 128 # Increased time horizon
    summary_freq: 5000 # Increased summary frequency
