behaviors:
  MovetoGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true # Use normalized inputs
      hidden_units: 256 # Increased hidden units
      num_layers: 3 # Increased number of layers
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    max_steps: 1000000 # Increased max steps
    time_horizon: 128 # Increased time horizon
    summary_freq: 5000 # Increased summary frequency
    threaded: true
    self_play:
      save_steps: 2000
      team_change: 10000
      swap_steps: 1000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
  FleefromAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true # Use normalized inputs
      hidden_units: 128 # Increased hidden units
      num_layers: 2 # Increased number of layers
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    max_steps: 1000000 # Increased max steps
    time_horizon: 128 # Increased time horizon
    summary_freq: 5000 # Increased summary frequency
    threaded: true
    self_play:
      save_steps: 2000
      team_change: 10000
      swap_steps: 1000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0